//
//  Logo.swift
//  DeepLinks
//
//  Created by Sergey Tarasov on 09.06.2022.
//

import Foundation

/// Simple model
struct Logo: Identifiable {
    var id: String
    var title: String
    var description: String
    var imageA: String
    var imageB: String
}

/// Global array of logos
let logos: [Logo] = [
    Logo(id: "logo1", title: "Logo 1", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "1a", imageB: "1b"),
    Logo(id: "logo2", title: "Logo 2", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "2a", imageB: "2b"),
    Logo(id: "logo3", title: "Logo 3", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "3a", imageB: "3b"),
    Logo(id: "logo4", title: "Logo 4", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "4a", imageB: "4b"),
    Logo(id: "logo5", title: "Logo 5", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "5a", imageB: "5b"),
    Logo(id: "logo6", title: "Logo 6", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "6a", imageB: "6b"),
    Logo(id: "logo7", title: "Logo 7", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "7a", imageB: "7b"),
    Logo(id: "logo8", title: "Logo 8", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "8a", imageB: "8b"),
    Logo(id: "logo9", title: "Logo 9", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "9a", imageB: "9b"),
    Logo(id: "logo10", title: "Logo 10", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "10a", imageB: "10b"),
    Logo(id: "logo11", title: "Logo 11", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "11a", imageB: "11b"),
    Logo(id: "logo12", title: "Logo 12", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed accumsan tellus mollis, semper augue eget, rutrum ante. Fusce et volutpat quam. Nulla porttitor arcu a mi viverra, a mattis ligula tempus. Aenean ac posuere enim, sit amet pretium elit. Sed eu tempus neque. Etiam semper ut arcu elementum elementum. Aliquam non sodales lacus, sit amet ultricies arcu. Nunc eget ullamcorper libero. Quisque vel blandit dui. Phasellus et lorem rhoncus odio ullamcorper accumsan. Mauris finibus placerat molestie. Donec velit eros, placerat sit amet tortor vel, euismod placerat quam. Cras sed odio sed quam vestibulum malesuada ac in nulla. Sed vel purus tempus libero feugiat blandit ut ac velit. Donec a turpis non tortor pellentesque tristique.", imageA: "12a", imageB: "12b")
]
